theme: minima

minima:
  skin: solarized


plugins:
  - jekyll-feed

title: tbd
description: tbd
collections:
  ine_updates:
    output: true
    permalink: /ine_updates/:path/
  analyses:
    output: true
    permalink: /analyses/:path/
