theme: minima
minima:
  skin: solarized

plugins:
  - jekyll-feed

title: INE-helper
# description: Este site tem o objetivo de facilitar o acesso aos dados do INE
collections:
  ine_updates:
    output: true
    permalink: /ine_updates/:path/
  analyses:
    output: true
    permalink: /analyses/:path/
